/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package photographyportfolio;

import java.awt.Image;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class userphoto extends javax.swing.JFrame {
    
    private List<byte[]> imageBytesList = new ArrayList<>();
   
    private JLabel[] imageLabels = new JLabel[8];
    
   
    /**
     * Creates new form userphoto
     */
    public userphoto() throws SQLException {
        initComponents();
        
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img1 = new javax.swing.JLabel();
        img5 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        img4 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        img6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        usern = new javax.swing.JLabel();
        clientusername = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 240, 200));
        getContentPane().add(img5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 210, 180));
        getContentPane().add(img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 210, 180));
        getContentPane().add(img4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 240, 210));
        getContentPane().add(img3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 210, 180));

        button1.setBackground(new java.awt.Color(204, 255, 153));
        button1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button1.setLabel("Next");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 560, -1, -1));

        button2.setBackground(new java.awt.Color(255, 102, 102));
        button2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        button2.setLabel("Privious");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, -1, -1));
        getContentPane().add(img6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 210, 180));

        jButton2.setBackground(new java.awt.Color(255, 204, 153));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setText("View Images");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photographyportfolio/photoport (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        usern.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        usern.setText("Ayush");
        getContentPane().add(usern, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, -1, -1));

        clientusername.setText("jLabel4");
        getContentPane().add(clientusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, -1, -1));

        setSize(new java.awt.Dimension(816, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void fetchImageDataFromDatabase() throws java.sql.SQLException {
        
        try{
         String username1 = usern.getText();
         java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/portfolio", "root", "root");
         java.sql.Statement stm = conn.createStatement();
         String query = "SELECT image1, image2, image3, image4, image5, image6 FROM user_gallary WHERE username = ?";
        java.sql.PreparedStatement preparedStatement = conn.prepareStatement(query);
        preparedStatement.setString(1, username1);

            java.sql.ResultSet resultSet = preparedStatement.executeQuery();
         
          if(resultSet.next()){
                    byte[] img = resultSet.getBytes("image1");
                    byte[] imgl2 = resultSet.getBytes("image2");
                    byte[] imgl3 = resultSet.getBytes("image3");
                    byte[] imgl4 = resultSet.getBytes("image4");
                    byte[] imgl5 = resultSet.getBytes("image5");
                    byte[] imgl6 = resultSet.getBytes("image6");
                    //Resize The ImageIcon
                    ImageIcon image = new ImageIcon(img);
                    ImageIcon image1 = new ImageIcon(imgl2);
                    ImageIcon image2 = new ImageIcon(imgl3);
                    ImageIcon image3 = new ImageIcon(imgl4);
                    ImageIcon image4= new ImageIcon(imgl5);
                    ImageIcon image5 = new ImageIcon(imgl6);
                    
                    Image im = image.getImage();
                    Image im2 = image1.getImage();
                    Image im3 = image2.getImage();
                    Image im4 = image3.getImage();
                    Image im5 = image4.getImage();
                    Image im6 = image5.getImage();
                    
                    
                    
                    ImageIcon newImage = new ImageIcon(im);
                    ImageIcon newImage1 = new ImageIcon(im2);
                    ImageIcon newImage2 = new ImageIcon(im3);
                    ImageIcon newImage3 = new ImageIcon(im4);
                    ImageIcon newImage4 = new ImageIcon(im5);
                    ImageIcon newImage5 = new ImageIcon(im6);
                    
                    img1.setIcon(newImage);
                    img2.setIcon(newImage1);
                    img3.setIcon(newImage2);
                    img4.setIcon(newImage3);
                    img5.setIcon(newImage4);
                    img6.setIcon(newImage5);
                }
               
                else{
                    JOptionPane.showMessageDialog(null, "No Data");
                }
            }catch(Exception ex){
                ex.printStackTrace();
            }
    
    }
    
    
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        usercontact usercontactFrame = new usercontact();
        usercontactFrame.username.setText(usern.getText());
        usercontactFrame.setVisible(true);
        usercontactFrame.pack();
        usercontactFrame.setLocationRelativeTo(usercontactFrame);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        String username = usern.getText();
         userinfo userinfoFrame = new userinfo(username);
         userinfoFrame.usernamelabel.setText(username);
       userinfoFrame.setVisible(true);
        userinfoFrame.pack();
        userinfoFrame.setLocationRelativeTo(userinfoFrame);
        this.dispose();      
    }//GEN-LAST:event_button2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            fetchImageDataFromDatabase();
        } catch (SQLException ex) {
            Logger.getLogger(userphoto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userphoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userphoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userphoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userphoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new userphoto().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(userphoto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    public javax.swing.JLabel clientusername;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel img4;
    private javax.swing.JLabel img5;
    private javax.swing.JLabel img6;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel usern;
    // End of variables declaration//GEN-END:variables
}
